import LayOut from '@/components/LayOut'
import './globals.css'
import { Inter } from 'next/font/google'
import Modal from '@/components/Modal'
import LoginModal from '@/components/LoginModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
     <LoginModal />
        <LayOut>
        {children}
        </LayOut>
  
        </body>
    </html>
  )
}
