import LayOut from '@/components/LayOut'
import './globals.css'
import { Inter } from 'next/font/google'
import Modal from '@/components/Modal'
import LoginModal from '@/components/LoginModal'
import RegisterModal from '@/components/RegisterModal'
import ToastProvider from '@/components/ToastProvider'
import { getSession } from '@/actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function   RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

const currentUser = await getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
     <LoginModal />
     <ToastProvider/>
     <RegisterModal />
        <LayOut currentUser={currentUser}>
        {children}
        </LayOut>
  
        </body>
    </html>
  )
}
